inlined check-and-execute and turned ~ to /home/linux for uniformity

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -1,5 +1,14 @@
 # importing scripts
-source ~/.scripts/check_and_execute.sh
+check_and_execute() {
+    local command="$1"
+    shift
+    if command -v "$command" >/dev/null 2>&1; then
+        "$command" "$@"
+        return $?
+    else
+        return 127
+    fi
+}
 
 # using zap for plugin management
 [ -f "$HOME/.local/share/zap/zap.zsh" ] && source "$HOME/.local/share/zap/zap.zsh" || zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh)
@@ -29,13 +38,13 @@ export PATH="$HOME/.local/bin:$PATH"
 export PATH="$HOME/bin:$PATH"
 
 # Sourcing .aliasrc
-[ -f ~/.aliasrc ] && source ~/.aliasrc || echo "Could not find ~/.aliasrc"
+[ -f $HOME/.aliasrc ] && source $HOME/.aliasrc || echo "Could not find ~/.aliasrc"
 
 # Sourcing LS_COLORS
-[ -f ~/.lscolors ] && source ~/.lscolors || echo "Could not find ls_colors file."
+[ -f $HOME/.lscolors ] && source $HOME/.lscolors || echo "Could not find ls_colors file."
 
 # Sourcing FZF config
-[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh || echo "Could not find fzf."
+[ -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh || echo "Could not find fzf."
 
 eval "$(check_and_execute zoxide init zsh)"
 
